### ISSUE TITLE
Footer does not always fill bottom of screen

### ISSUE THREAD

**Issue by stpaultim** [backdrop-contrib/snazzy#1]
If there is not enough content on the screen, the footer can sometimes float above a white bar at the bottom of the screen. 

I believe that the default should be to prevent any white space from appearing below the footer. 

![snazzy](https://user-images.githubusercontent.com/3144571/102724020-f7ec7900-42d1-11eb-9d7b-9a2515bd9508.png)

**Comment by indigoxela** [comment]
> I believe that the default should be to prevent any white space from appearing below the footer

You might be right, I didn't consider that yet.

**Comment by indigoxela** [comment]
Does the [latest commit](https://github.com/backdrop-contrib/snazzy/commit/1ec8520642745065302001a6ea5cb7b89ab0892b) fix it for you?

**Comment by stpaultim** [comment]
Yes it does. Thanks. It looks much better now.
