### ISSUE TITLE
Problems with header on mobile

### ISSUE THREAD

**Issue by stpaultim** [backdrop-contrib/snazzy#2]
Here is a screenshot of my test site as seen on my Android cell phone. 

The site is pretty basic with some very simple content (sorry about the volume widget being open).

there is white space on the left side of image, but not on the right side.

![Screenshot_20201220-145453](https://user-images.githubusercontent.com/3144571/102724231-cb396100-42d3-11eb-9ba5-4ed13ce8c56c.png)

**Comment by indigoxela** [comment]
Hi @stpaultim, many thanks for reporting.

> there is white space on the left side of image, but not on the right side.

Do you happen to know your cell phone's screen resolution?

**Comment by stpaultim** [comment]
This is the specs on my cell phone:

https://www.gsmarena.com/motorola_moto_g5_plus-8453.php

According to http://whatismyscreenresolution.net/ the resolution of my screen is 360px x 640px.

But, I think you fixed this already.

![Screenshot_20201222-222018](https://user-images.githubusercontent.com/3144571/102959471-35edc680-44a5-11eb-9403-944ccd02ee5e.png)
