### ISSUE TITLE
Link hover doesn't work for multiline links

### ISSUE THREAD

**Issue by olafgrabienski** [backdrop-contrib/snazzy#3]
This theme has a nice link hover behavior, a 2px animated underline via *border-bottom*. However, if a link is multiline, e.g. in a body text field, it gets only underlined for one line when you hover over it.

Screenshot:

![backdrop-snazzy-link-hover](https://user-images.githubusercontent.com/14188307/127460217-69af5c45-9bae-4480-8231-408f7ede754d.png)

**Comment by olafgrabienski** [comment]
For reference the relevant CSS link definitions of the theme:

https://github.com/backdrop-contrib/snazzy/blob/1.x-1.x/css/style.css#L6:
```
a {
  text-decoration: none;
  position: relative;
}
```

https://github.com/backdrop-contrib/snazzy/blob/1.x-1.x/css/style.css#L92:
```
.layout a::after {
  content: "";
  display: inline-block;
  border-bottom: 2px solid;
  width: 0;
  height: 0;
  position: absolute;
  bottom: 0;
  left: 50%;
  transition: left 0.2s, width 0.2s;
}
```

https://github.com/backdrop-contrib/snazzy/blob/1.x-1.x/css/style.css#L109:
```
a:hover::after {
  width: 100%;
  left: 0;
}
```

**Comment by indigoxela** [comment]
@olafgrabienski many thanks for opening this issue.

As I already wrote in the chat - I'm not able to solve this (without severe side-effects), so a PR is welcome. :+1:

**Comment by olafgrabienski** [comment]
> I'm not able to solve this (without severe side-effects), so a PR is welcome.

I've got something, a modification of a solution presented on https://www.dannyguo.com/blog/animated-multiline-link-underlines-with-css:

```
a {
  background-image: linear-gradient(currentColor, currentColor);
  background-position: center 100%;
  background-repeat: no-repeat;
  background-size: 0% 2px;
  transition: background-size 0.2s;
}
a:hover {
  background-size: 100% 2px;
}
```

Main difference to the mentioned solution is the ` background-position` value `center 100%` (instead of `0% 100%`) to make sure the animation moves outward (instead from left to right).

And in contrast to the current hover implementation in *Snazzy*, I don't use the `::after` pseudo-element but just the link as selector. @indigoxela What do you think about side-effects?

**Comment by indigoxela** [comment]
This looks promising! Many thanks for sharing this alternate solution.

**Comment by indigoxela** [comment]
Here's a PR/branch with that new approach.

One problem: the color.css file needed changes, which means that people who use a different color profile (provided or custom) will have to save their theme settings once to get that (generated by color module) file updated.

Themes have no update hooks, so we have to instruct them, probably in the release message. And the chance should be bigger that people read that, if the version is a minor release (1.x-1.1.0) or possibly a major (1.x-2.0.0).

@olafgrabienski what do you think?

**Comment by olafgrabienski** [comment]
Thanks for the PR! I've made the same changes to my test site, and they work like a charm.

Drawing attention to the release notes via a new major version number `1.x-2.0.0` sounds like a good idea, also because `1.x-1.1.0` and `1.x-1.0.1` look quite similar.

**Comment by indigoxela** [comment]
Hm... thinking this over.
Sure, themes have no update hooks, but flushing all caches also lets the Color module rebuild/regenerate its CSS files.

So, if somebody updates via UI, and walks through all the steps, caches get flushed and the new style is working.
If somebody does updates via FTP or whatever, they're supposed to flush caches manually. Otherwise no changes would apply to the aggregated asset files (.css, .js).

In fact, I think a normal "patch release" (1.x-1.0.2) could be OK. :thinking:

**Comment by olafgrabienski** [comment]
> I think a normal "patch release" (1.x-1.0.2) could be OK.

Sounds reasonable! (A hint in the release message about flushing caches and about the new link hover approach wouldn't hurt, though.)

**Comment by indigoxela** [comment]
> Sounds reasonable! ...

Yes, at first sight, but then... I think, I just had another learning curve about Backdrop internals. :stuck_out_tongue_winking_eye: My first impression, that people have to save the settings once seems correct. Otherwise only the query string for css/js gets updated, but the files don't.
Today doesn't seem to be the best day for me to figure out things, I'll give it another try, when I'm less confused. :laughing:

**Comment by olafgrabienski** [comment]
> My first impression, that people have to save the settings once seems correct. 

So, if that's the case, shall we come back to the idea of a new major version number `1.x-2.0.0`, plus informative release notes?
