### ISSUE TITLE
Contextual links not working

### ISSUE THREAD

**Issue by olafgrabienski** [backdrop-contrib/snazzy#5]
As of [release 1.1.0](https://github.com/backdrop-contrib/snazzy/releases/tag/1.x-1.1.0), I don't see no more contextual links on my site, when *Snazzy* is the default theme. I guess, this is a side-effect of [multiline support to link animation](https://github.com/backdrop-contrib/snazzy/issues/3).

In #3, the *border-bottom* approach was replaced by animating (the size of) a linear-gradient background-image. This change seems to hide contextual links, removing the *gear-select* background-image of contextual links (around [line 102](https://github.com/backdrop-contrib/snazzy/commit/b02c2e42f3e020105f97179a03eb271ad2bebd8e#diff-1fc556f95754ee7e33d91044125c44bb9f750c99be4406756ffb27413adfcaf5R102) of the commit).

I was able to fix the contextual links in a *Snazzy* sub-theme using the following CSS rules:

```
.contextual-links-wrapper > a {
  background-image: url(/core/modules/contextual/images/gear-select.png);
}
.contextual-links-wrapper > a:hover {
  background-size: auto;
}
```

Haven't tested it extensively, though. Is it the right approach? We should probably also check if other elements are affected similarly.

**Comment by indigoxela** [comment]
@olafgrabienski nice catch! Does the [PR](https://github.com/backdrop-contrib/snazzy/pull/6) fix it for you?

**Comment by olafgrabienski** [comment]
Thanks, it does! (And using `not` looks also good.)
